### ISSUE TITLE
Project name might be legally problematic

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [collinsmith/diablo#5]
IANAL, but it might be legally problematic (and get this interesting project shut down) unless you change name to something that sounds a bit less exactly like Blizzard's IP (intellectual property).

Also (kind of relevant when it comes to naming) have you heard of OpenD2 (https://github.com/eezstreet/OpenD2)? You might benefit from some cooperation or something.

Off topis: I hope your thing becomes as awesome as VCMI is for HoMM3. Also personally I value a compatibility mode a lot which lets you play near vanilla, but whatevs, your project, your labor. :+1:

**Comment by collinsmith** [comment]
Yes, I have considered this, but I didn't want to dwell on a name. I still view this very much as a personal project, and the name is a placeholder. I did not expect this project to receive much, if any, attention ... at least not yet.

I've looked at tons of other projects/resources, but the real fun for me is trying to work it out for myself.

I would love to include options for a classic mode, and some of the changes I have in mind will be easy to configure via cvars (e.g., auto-pickup gold is one idea). I am just not far enough along to give it much more thought than that. As of now I am not planning on supporting vanilla characters (i.e., non-expansion) and before patch 1.14, and I don't think this is a problem for the vast majority of players.
